# Generated by Django 5.1.1 on 2024-10-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produtos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo',
            field=models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Código Produto'),
        ),
    ]
