# Generated by Django 5.1.1 on 2024-10-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_produto_alter_produtos_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('data_nascimeto', models.DateField(verbose_name='Data nascimento')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefonte', models.BigIntegerField(help_text='inserir numero com DDD', verbose_name='telefone')),
                ('codigo_produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.produtos')),
            ],
        ),
    ]
